CREATE DATABASE IF NOT EXISTS mydb;
CREATE DATABASE IF NOT EXISTS mydb_test;

CREATE USER IF NOT EXISTS 'devuser'@'%' IDENTIFIED BY 'devpass';
GRANT ALL PRIVILEGES ON mydb.* TO 'devuser'@'%';
GRANT ALL PRIVILEGES ON mydb_test.* TO 'devuser'@'%';
FLUSH PRIVILEGES;
